- type: playTimeTracker
  id: JobCentralCommandAdmiral

- type: playTimeTracker
  id: InteQVanguardLeader

- type: playTimeTracker
  id: InteQVanguard

- type: playTimeTracker
  id: JobERTInteQVanguardLeader

- type: playTimeTracker
  id: JobERTInteQVanguard

- type: playTimeTracker
  id: JobDeathSquadLeader

- type: playTimeTracker
  id: JobBitrunner

- type: playTimeTracker
  id: JobBitrunAvatar
