using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Mini.Ratvar.Roles;

[GenerateTypedNameReferences]
public sealed partial class RatvarRoundStartMenu : FancyWindow
{
    public RatvarRoundStartMenu()
    {
        RobustXamlLoader.Load(this);
        ConfirmButton.OnPressed += _ => Close();
    }
}
