// SPDX-FileCopyrightText: 2022 E F R <602406+Efruit@users.noreply.github.com>
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;
using Content.Client._Amour.Stickers.UI;
using Robust.Shared.IoC;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using System.Numerics;
using System.Text.RegularExpressions;
using Robust.Shared.Log;

namespace Content.Client.Administration.UI.Bwoink
{
    [GenerateTypedNameReferences]
    public sealed partial class BwoinkPanel : BoxContainer
    {
        private readonly Action<string> _messageSender;

        public int Unread { get; private set; } = 0;
        public DateTime LastMessage { get; private set; } = DateTime.MinValue;
        private List<string> PeopleTyping { get; set; } = new();
        public event Action<string>? InputTextChanged;

        public BwoinkPanel(Action<string> messageSender)
        {
            RobustXamlLoader.Load(this);

            var msg = new FormattedMessage();
            msg.PushColor(Color.LightGray);
            msg.AddText(Loc.GetString("bwoink-system-messages-being-relayed-to-discord"));
            msg.Pop();
            RelayedToDiscordLabel.SetMessage(msg);

            _messageSender = messageSender;

            OnVisibilityChanged += c =>
            {
                if (c.Visible)
                    Unread = 0;
            };
            SenderLineEdit.OnTextEntered += Input_OnTextEntered;
            SenderLineEdit.OnTextChanged += Input_OnTextChanged;

            // Amour edit start
            StickerBtn.OnStickerSelected += sticker => StickerInputHelper.InsertSticker(SenderLineEdit, sticker);
            // Amour edit end

            UpdateTypingIndicator();
        }

        private void Input_OnTextEntered(LineEdit.LineEditEventArgs args)
        {
            if (string.IsNullOrWhiteSpace(args.Text))
                return;

            _messageSender.Invoke(args.Text);
            SenderLineEdit.Clear();
        }

        private void Input_OnTextChanged(LineEdit.LineEditEventArgs args)
        {
            InputTextChanged?.Invoke(args.Text);
        }

        public void ReceiveLine(SharedBwoinkSystem.BwoinkTextMessage message)
        {
            if (!Visible)
                Unread++;

            var regex = new System.Text.RegularExpressions.Regex(@"\[icon=(?<path>[^\]]+)\]");
            var match = regex.Match(message.Text);

            // Горизонтальная строка сообщения
            var line = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalAlignment = HAlignment.Left,
                VerticalAlignment = VAlignment.Top,
                Margin = new Thickness(0, 2),
                MinHeight = 24
            };

            // Время (серое)
            var timeLabel = new RichTextLabel();
            var timeMsg = new FormattedMessage(1);
            timeMsg.AddMarkupOrThrow($"[color=gray]{message.SentAt.ToShortTimeString()}[/color] ");
            timeLabel.SetMessage(timeMsg);
            line.AddChild(timeLabel);

            if (match.Success)
            {
                var iconPath = match.Groups["path"].Value;
                // Текст до маркера (должность)
                var before = message.Text.Substring(0, match.Index);
                if (!string.IsNullOrEmpty(before))
                {
                    var beforeLabel = new RichTextLabel();
                    var beforeMsg = new FormattedMessage(1);
                    beforeMsg.AddMarkupOrThrow(before);
                    beforeLabel.SetMessage(beforeMsg);
                    line.AddChild(beforeLabel);
                }

                try
                {
                    var resourceCache = IoCManager.Resolve<IResourceCache>();
                    var texture = resourceCache.GetResource<TextureResource>(iconPath);
                    var icon = new TextureRect
                    {
                        Texture = texture,
                        Stretch = TextureRect.StretchMode.KeepAspectCentered,
                        MinSize = new Vector2(20, 20),
                        MaxSize = new Vector2(24, 24),
                        Margin = new Thickness(4, 0, 4, 0),
                        VerticalAlignment = VAlignment.Center
                    };
                    line.AddChild(icon);
                }
                catch { }

                // Текст после маркера (имя и сообщение)
                var after = message.Text.Substring(match.Index + match.Length);
                if (!string.IsNullOrEmpty(after))
                {
                    var afterLabel = new RichTextLabel();
                    var afterMsg = new FormattedMessage(1);
                    afterMsg.AddMarkupOrThrow(after);
                    afterLabel.SetMessage(afterMsg);
                    line.AddChild(afterLabel);
                }
            }
            else
            {
                // Без иконки – просто весь текст
                var textLabel = new RichTextLabel();
                var textMsg = new FormattedMessage(1);
                textMsg.AddMarkupOrThrow(message.Text);
                textLabel.SetMessage(textMsg);
                line.AddChild(textLabel);
            }

            // Добавляем строку в вертикальный контейнер TextOutput
            TextOutput.AddChild(line);
            LastMessage = message.SentAt;
        }

        private void UpdateTypingIndicator()
        {
            var msg = new FormattedMessage();
            msg.PushColor(Color.LightGray);

            var text = PeopleTyping.Count == 0
                ? string.Empty
                : Loc.GetString("bwoink-system-typing-indicator",
                    ("players", string.Join(", ", PeopleTyping)),
                    ("count", PeopleTyping.Count));

            msg.AddText(text);
            msg.Pop();

            TypingIndicator.SetMessage(msg);
        }

        public void UpdatePlayerTyping(string name, bool typing)
        {
            if (typing)
            {
                if (PeopleTyping.Contains(name))
                    return;

                PeopleTyping.Add(name);
                Timer.Spawn(TimeSpan.FromSeconds(10), () =>
                {
                    if (Disposed)
                        return;

                    PeopleTyping.Remove(name);
                    UpdateTypingIndicator();
                });
            }
            else
            {
                PeopleTyping.Remove(name);
            }

            UpdateTypingIndicator();
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);

            InputTextChanged = null;
        }
    }
}
