using Content.Client.Info;
using Content.Client.UserInterface.Systems.EscapeMenu;
using Content.Client.UserInterface.Systems.Guidebook;
using Content.Shared._CorvaxGoob.CCCVars;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Player;
using Robust.Shared.Configuration;
using Content.Client.UserInterface.Systems.Ghost.Controls;
using Content.Client.Stylesheets;
using Robust.Client.UserInterface.Controls;
using Content.Client.UserInterface.Systems.Ghost;
using Content.Shared.Ghost;
using Content.Client.Ghost;
using Content.Client.UserInterface.Systems.Ghost;
using Content.Client.ADT.Roadmap;
// using Content.Goobstation.Client.Patron;

namespace Content.Client.Lobby.UI

{
    [GenerateTypedNameReferences]
    public sealed partial class LobbyGui : UIScreen
    {
        [Dependency] private readonly IClientConsoleHost _consoleHost = default!;
        [Dependency] private readonly IUserInterfaceManager _userInterfaceManager = default!;
        [Dependency] private readonly IUriOpener _uriOpener = default!;
        [Dependency] private readonly IPlayerManager _playerManager = default!;
        [Dependency] private readonly IConfigurationManager _cfg = default!;
        [UISystemDependency] private readonly GhostSystem? _system = default;

        [UISystemDependency] private readonly GhostSystem _ghostSystem = default!;
        public event Action? GhostRolesPressed;

        private int _prevNumberRoles;

        public GhostTargetWindow TargetWindow { get; } = null!;

        public LobbyGui()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            SetAnchorPreset(MainContainer, LayoutPreset.Wide);
            SetAnchorPreset(Background, LayoutPreset.Wide);

            LeaveButton.OnPressed += _ => _consoleHost.ExecuteCommand("disconnect");
            OptionsButton.OnPressed += _ => UserInterfaceManager.GetUIController<OptionsUIController>().ToggleWindow();

            AuthorizationDiscordButton.OnPressed += _ =>
            {
                var userId = _playerManager.LocalSession?.UserId;
                var requestUrl = $"{_cfg.GetCVar(CCCVars.DiscordAuthApiUrl)}/login/{userId.ToString()}";
                _uriOpener.OpenUri(new Uri(requestUrl));
            };

            Boosty.OnPressed += _ => _uriOpener.OpenUri(new Uri("https://boosty.to/mini-station"));
            Discord.OnPressed += _ => _uriOpener.OpenUri(new Uri("https://discord.gg/mini-station"));
            Telegram.OnPressed += _ => _uriOpener.OpenUri(new Uri("https://t.me/mini_station"));
            CharacterSetup.OnPressed += _ => SwitchState(LobbyGuiState.CharacterSetup);
            Rules.OnPressed += _ => new RulesAndInfoWindow().Open();
            Guidebook.OnPressed += _ => UserInterfaceManager.GetUIController<GuidebookUIController>().ToggleGuidebook();
            // Changelog.OnPressed += _ => UserInterfaceManager.GetUIController<ChangelogUIController>().ToggleWindow();

            RoadmapButton.OnPressed += _ => UserInterfaceManager.GetUIController<RoadmapUIController>().ToggleRoadmap();
        }

        public void SwitchState(LobbyGuiState state)
        {
            switch (state)
            {
                case LobbyGuiState.Default:
                    CharacterSetupState.Visible = false;
                    SplitContainer.Visible = true;
                    break;
                case LobbyGuiState.CharacterSetup:
                    CharacterSetupState.Visible = true;
                    SplitContainer.Visible = false;
                    UserInterfaceManager.GetUIController<LobbyUIController>().ReloadCharacterSetup();
                    break;
            }
        }

        public enum LobbyGuiState : byte
        {
            /// <summary>
            ///  The default state, i.e., what's seen on launch.
            /// </summary>
            Default,

            /// <summary>
            ///  The character setup state.
            /// </summary>
            CharacterSetup
        }


    }
}
