using System.Collections.Generic;
using System.Numerics;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.RPSX.DarkForces.Ratvar.Prototypes;
using Content.Shared.RPSX.DarkForces.Ratvar.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using System.Linq;

namespace Content.Client.RPSX.DarkForces.Ratvar.Structures;

[GenerateTypedNameReferences]
public sealed partial class RatvarWorkshopWindow : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IEntitySystemManager _entitySystem = default!;

    public Action<EntProtoId, int, int, int>? OnCraftPressed;

    private readonly SpriteSystem _spriteSystem;
    private readonly HashSet<RatvarCraftCategoryPrototype> _categories;
    private readonly Color _categoryBackgroundColor;

    public RatvarWorkshopWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _spriteSystem = _entitySystem.GetEntitySystem<SpriteSystem>();
        _categories = _prototype.EnumeratePrototypes<RatvarCraftCategoryPrototype>().ToHashSet();

        Color.TryParse("#25252a80", out _categoryBackgroundColor);
    }

    public void UpdateState(RatvarWorkshopUIState state)
    {
        var brass = state.Brass / 100;
        var power = state.Power;

        BrassCount.Text = $"{brass}";
        PowerCount.Text = $"{power}";
        ProgressState.Text = state.InProgress ? "В работе" : "Готово к работе";

        CraftList.RemoveAllChildren();
        CreateReceipts(brass, power, state.InProgress);
    }

    private void CreateReceipts(int brass, int power, bool inProgress)
    {
        foreach (var category in _categories)
        {
            var categoryLabel = new Label
            {
                Text = Loc.GetString(category.Name),
                StyleClasses = { "LabelKeyText" },
                Margin = new Thickness(8, 8, 8, 4)
            };
            CraftList.AddChild(categoryLabel);

            var divider = new PanelContainer
            {
                StyleClasses = { "LowDivider" },
                Margin = new Thickness(8, 0, 8, 8)
            };
            CraftList.AddChild(divider);

            foreach (var receiptProtId in category.Receipts)
            {
                var receipt = _prototype.Index(receiptProtId);
                var receiptBrassCost = receipt.BrassCost / 100;
                var receiptPowerCost = receipt.PowerCost;
                var canCraft = !inProgress && receiptBrassCost <= brass && receiptPowerCost <= power;

                var receiptPanel = new PanelContainer
                {
                    PanelOverride = new StyleBoxFlat
                    {
                        BackgroundColor = _categoryBackgroundColor,
                    },
                    Margin = new Thickness(8, 2)
                };

                var receiptContainer = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                    Margin = new Thickness(8, 4)
                };

                var textureRect = new TextureRect
                {
                    Texture = _spriteSystem.Frame0(receipt.Icon),
                    TextureScale = new Vector2(1.5f, 1.5f),
                    Stretch = TextureRect.StretchMode.KeepCentered,
                    MinSize = new Vector2(32, 32),
                    Margin = new Thickness(0, 0, 8, 0)
                };

                var button = new Button
                {
                    Text = Loc.GetString(receipt.Name),
                    MaxHeight = 28f,
                    MinWidth = 150,
                    Margin = new Thickness(0, 0, 8, 0),
                    Disabled = !canCraft
                };

                var requirementsLabel = new Label
                {
                    Text = $"Латунь: {receiptBrassCost}, Энергия: {receiptPowerCost}",
                    StyleClasses = { StyleBase.StyleClassLabelSubText },
                    Align = Label.AlignMode.Right,
                    Margin = new Thickness(0, 0, 8, 0),
                    HorizontalExpand = true,
                    VerticalAlignment = VAlignment.Center
                };

                var currentReceipt = receipt;
                button.OnPressed += _ =>
                    OnCraftPressed?.Invoke(currentReceipt.EntityProduce,
                                          currentReceipt.BrassCost,
                                          currentReceipt.PowerCost,
                                          currentReceipt.CraftingTime);

                receiptContainer.AddChild(textureRect);
                receiptContainer.AddChild(button);
                receiptContainer.AddChild(requirementsLabel);

                receiptPanel.AddChild(receiptContainer);
                CraftList.AddChild(receiptPanel);
            }
        }
    }
}
